### ISSUE TITLE
Code Climate compliance

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#1006]
Ensure all pre-existing code passes code climate. Entails fixing all current issues. 

Will be a substantial contribution that shouldn't be very difficult, but will increase dev's familiarity with code base substantially.

**Comment by mnm364** [comment]
Just want to point out: I disagree that this will not be very difficult, but a worthwhile undertaking for the ambitious soul! Happy to help if someone wants to take this project!

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
