### ISSUE TITLE
Full parse Profiler

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#1007]
Design a system to profile the "goodness" of a parse. In its current idealization, the Profiler will be a set of metrics (potentially visual charts as well).

Some ideas:
- [ ] Sections per unique course
- [ ] unique professors
- [ ] distribution of 12hr and 24hr time ranges
- [ ] Splitting up name into first and last
- [ ] Unique builidings
- [ ] lists are not built up as the parse progress (i.e. failure to clear information)

The general principle is that the more detailed information we can get, the better we can harness information to develop features and affect the product at its core!
_____________________________

This Profiler should be subclassed from the `parsing.library.viewer.Viewer` and be able to iteratively add on more metrics as more are developed.
____________
Similar but not the same as #552

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
