### ISSUE TITLE
Google Login, gCal + iCal Download broken

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1017]
Trying to login with Google gives you an authorization error
<img width="1280" alt="screen shot 2017-08-31 at 5 24 47 pm" src="https://user-images.githubusercontent.com/14956724/29977201-92f13ece-8f0a-11e7-91db-28d1e3497ecd.png">

On the live server right now trying to download your google cal or iCal it loads infinitely. On master it just downloads or adds an empty calendar.

**Comment by ecalder6** [comment]
This is still broken and have been reported by Hopkins students.

**Comment by kristinyim** [comment]
I'll be working on this for now.

**Comment by kristinyim** [comment]
@noahpresler Could you give me some pointers on this? I can't login to my google acc on local so I can't even start to debug it. I get a 403 error which I think has to do with my dev credentials - there's already a secret key on the file but maybe I need a new one? Where/How do I get that. Login with google works fine on prod so I'm pretty sure its this.

**Comment by kristinyim** [comment]
Fixed gCal download but now need to stop the modal from constantly popping back up after it has been closed.

**Comment by andrewwong97** [comment]
Modal popup bug can be fixed by changing `ActionTypes.TRIGGER_SAVE_CALENDAR_MODAL` in line 94 of `modal_actions.jsx` to `ActionTypes.TOGGLE_SAVE_CALENDAR_MODAL`, just minor typo

![image](https://user-images.githubusercontent.com/7339169/35775873-80097540-095f-11e8-9b1f-056543fe04b9.png)

**Comment by Boccca2014** [comment]
Resolved in new repo!
