### ISSUE TITLE
Study-Helper App

### ISSUE THREAD

**Issue by mason2smart** [noahpresler/semesterly#1027]
App that promotes good study habits by utilizing students' schedules and provided breakfast, lunch, and dinner times to analyze the schedule for large blocks of time for studying. The app will then list the two closest places to the student's previous class or to the students next class that a student can go to to study, with options for different majors that have their own study spaces. 
Optionally allows the student to input them into a schedule with their location so freshman can find them. 

HopHacks2017
Mason Cole, Alyssa Thomas, Tony Yang, Nancy Wang

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!

**Comment by mason2smart** [comment]
@Boccca2014 see studyfire repo here: https://github.com/mason2smart/StudyFire
