### ISSUE TITLE
HEART Courses

### ISSUE THREAD

**Issue by hdesai4204** [noahpresler/semesterly#1029]
Problem:
The current HEART courses are listed under the same name: "Heart: Introduction to Numerical Analysis and Simulation in Engineering". The different sections have the proper times and teacher, but the name for each section needs to be fixed. 

Solutions:
I'm not entirely sure how to fix this. My hypothesis of how this problem originated is that it would have been too complicated or confusing to list each HEART course individually since there are 41 HEART sections. However, some HEART courses have multiple sections on different days and share the same name. Can anyone propose a solution?

**Comment by mnm364** [comment]
#382

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
