### ISSUE TITLE
Professor Evaluation Options

### ISSUE THREAD

**Issue by mason2smart** [noahpresler/semesterly#1030]
- Option to sort professor evaluations by their ratings

- Option to view professor evaluations for all courses the professor has taught

- If no evaluation exists for a specific course for a professor that is now teaching it and the professor has reviews for other courses offer to redirect to see reviews on professor for other courses the professor taught

HopHacks - Fall2017
Mason Cole, Alyssa Thomas, Tony Yang, Nancy Wang

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
