### ISSUE TITLE
new_school

### ISSUE THREAD

**Issue by cmw025** [noahpresler/semesterly#1034]
I'd like to add a Bucknell University.
I have followed the documentation to get my local development environment set up, but I could need some help developing the parser.
https://www.bucknell.edu/

**Comment by ryanhugh** [comment]
Yo! I'm the developer of Search NEU (https://github.com/ryanhugh/searchneu) which is a search box for all the classes at Northeastern. To get the data I'm scraping Northeastern's registration website. Looks like bucknell (and TONS of other schools) use the same registration website as NEU so we should be able to use the same code to scrape both of them! I'll take a look to see if I can scrape bucknell's website tonight or tomorrow with the Search NEU scrapers. It might need some tweaks but it shouldn't be that hard to get working. I'll post and update once I give it a shot. 

This is Bucknell's registration system, right?
https://www.bannerssb.bucknell.edu/ERPPRD/bwckctlg.p_disp_dyn_ctlg

**Comment by ryanhugh** [comment]
I just took a stab at it and was able to scrape all the data for bucknell. It took about 8 minutes to scrape 2 semesters. Attached

[Archive.zip](https://github.com/noahpresler/semesterly/files/1322804/Archive.zip)

**Comment by cmw025** [comment]
Awesome! Search NEU looks pretty polished and it's fantastic news you
already got the scraper to work! Anything I'd be able to contribute? I'd
love to join the development!

**Comment by ryanhugh** [comment]
Yeah!! Thanks! I was chatting with some of the developers of Semester.ly over Facebook and I am going to take a stab at converting the Search NEU schema to the Semeter.ly schema so we can add support for NEU (and every other school that uses Banner, such as Bucknell). 

I'm pretty busy with school and everything but it shouldn't be too hard to convert the schema. I should be able to find some time over the next couple weeks. 

In the meantime, if you want to work on Semester.ly in general that would be awesome! You should get in contact with someone on the Semester.ly team. If there is anything else you are interested in working on (Search NEU, adding support for NEU/Bucknell to Semester.ly, etc) to you can totally work on that too! Just let us know.

**Comment by Boccca2014** [comment]
Hi,

This repository is now deprecated as of June 2021.
The new repository can be found [HERE](https://github.com/jhuopensource/semesterly).
If you still wish to integrate your university, note any issues, or make any suggestions, please place them in the new repository. Thank you!

Best,

Sebastian (@Boccca2014)
Current Program Manager of [Semester.ly](https://semester.ly/)
