### ISSUE TITLE
Add a Clubs Section to Semester.ly

### ISSUE THREAD

**Issue by mason2smart** [noahpresler/semesterly#1035]
Add a clubs section that allows students to select clubs they are interested in and see meeting times and locations and allow export in calendar.

Tired of clubs announcing meetings the day of or day before. A central place for all club schedules would be great and would not only promote better club organization but allow for greater student involvement.

**Comment by Boccca2014** [comment]
@Boccca2014 Excellent idea, Will try to do in the new repo!
