### ISSUE TITLE
General Docs Issues

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#1038]
- [ ] Add section at beginning of "Installation" listing supported OSs
- [ ] for `etc/hosts` pull lists of schools from `parsing/schools/active` file in repo
Maybe something like so...
```
sudo sh -c "cat parsing/schools/active | xargs -I {} echo '{}.sem.ly' | tr '\n' ' ' | xargs -I {} echo -e '127.0.0.1\tsem.ly {}' >> /etc/hosts"
```
- [ ] take away `sudo` in `sudo npm install` (well seeing issue but you shouldn't need `sudo`... **nah** it just fails either way :-1: #1025)
This actually turned into an issue. I am running a clean Ubuntu 16.04.3 build. It seems that `sudo apt install nodejs npm` will install node version 4.2.6 which npm does not support. I had to resort to the following and then `npm install` (without `sudo`) worked.
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

- [ ] `requests`, `numpy` and `scipy` need be by installed before `pip install -r requirements.txt` 
- [ ] Add "text shot" of what it looks like when you log into the database
- [ ] Under `Create Local Settings` it is unclear which `semesterly` directory `local_settings` should be placed under
- [ ] Specify shell(s) this has been tested under. I was trying to this in `fish` and running into issues. I think these instructions were written under `zsc`.
- [ ] Phantomjs link to PATH does not exist (try `sudo apt install phantomjs`)
- [ ] `npm install -g webpack chromedriver` does not work (trying sudo now). Well that didnt work either... but i dont even think this step is needed.
- [ ] Had to manually install `npm install node-sass`
- [ ] After following instructions cleanly on new build `python manage.py test` yields:
```
Creating test database for alias 'default'...
Got an error creating the test database: permission denied to create database

Type 'yes' if you would like to try deleting the test database 'test_semesterly', or 'no' to cancel: yes
Destroying old test database for alias 'default'...

Got an error recreating the test database: database "test_semesterly" does not exist
```
This can be [solved](https://stackoverflow.com/questions/14186055/django-test-app-error-got-an-error-creating-the-test-database-permission-deni) by adding `ALTER USER myusername CREATEDB;` to the database setup

**Comment by mnm364** [comment]
- [ ] Elasticsearch install bug
https://stackoverflow.com/questions/31677563/connection-refused-error-on-elastic-search

**Comment by kristinyim** [comment]
At python manage.py migrate, some people will get errors that Django is not installed when in fact it is but in a different version of Python. Maybe at details about this to the docs

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
