### ISSUE TITLE
Professor/Class Office Hours&Locations

### ISSUE THREAD

**Issue by mason2smart** [noahpresler/semesterly#1040]
Adding a form for students/teachers to infill office hours for classes would be helpful. Also should allow students to download a separate calendar file with them.

it could be as simple as storing information by class/section/teacher/year/hours/location in a text document or file stored on the server with a few simple java-script methods that use line-based search/edit to find/change information (this method is not the best way but its really easy to implement)

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
