### ISSUE TITLE
Improper validation schema

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#1046]
When the Validator picks the schema based on the `kind` of the ingesting object, it fails to pick the correct level of validation. For example: validating a section from the ingestor will use the schema found in `parsing/library/schemas/section.json`, however, it should be using `parsing/library/schemas/section_only.json`. This leads to **minor** ways to bypass some aspect of validation (e.g. not including year in a section) and needs to be patched. The issue is that this resolution will affect deeper implementation details.

**Comment by Boccca2014** [comment]
@Boccca2014 Will check in new repo
