### ISSUE TITLE
Add pilot integration shows for non-privileged users 

### ISSUE THREAD

**Issue by ecalder6** [noahpresler/semesterly#1050]
![image](https://user-images.githubusercontent.com/8675242/32060851-ff5680de-ba3d-11e7-9036-9b97f05c3623.png)

**Comment by ecalder6** [comment]
Hotfix on a7c5ef4

**Comment by Boccca2014** [comment]
@Boccca2014 Will integrate into new repo if PILOT wishes to rejoin
