### ISSUE TITLE
Wrong Prereqs

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1052]
Some classes are displaying the wrong pre-requirements for classes:

Looks like its a back-end issue:
![image](https://user-images.githubusercontent.com/14956724/32069007-e3f12728-ba55-11e7-8fbd-fc35e5fdee90.png)

# **Example 1:**
<img width="1280" alt="screen shot 2017-10-26 at 10 34 38 am" src="https://user-images.githubusercontent.com/14956724/32062658-221608c4-ba43-11e7-86d3-1348dd602a96.png">
<img width="1280" alt="screen shot 2017-10-26 at 10 33 27 am" src="https://user-images.githubusercontent.com/14956724/32062671-2eaab47c-ba43-11e7-913e-af2bd23f5d63.png">

# **Example 2:**
<img width="1280" alt="screen shot 2017-10-26 at 11 46 53 am" src="https://user-images.githubusercontent.com/14956724/32062737-65efb4b4-ba43-11e7-807d-df09a2f0c335.png">
<img width="1280" alt="screen shot 2017-10-26 at 10 52 30 am" src="https://user-images.githubusercontent.com/14956724/32062742-69430c56-ba43-11e7-8d68-34a801f42566.png">

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
