### ISSUE TITLE
Changing Tutorial Images to SVGs

### ISSUE THREAD

**Issue by stewy33** [noahpresler/semesterly#1067]
When using semesterly for the first time, I noticed that the tutorial images were quite blurry, although still readable. They are raster .png images, but look like they could definitely be converted to the vector-based .svg format.
I understand that IE8 and lower cannot handle svgs, but I think it would be reasonable to convert the tutorial, and possibly other images to svgs since they look better as they scale, are smaller files.
How would we go about doing this? I'm sure it wouldn't be hard for the designer of the images, but I am willing to help out. And is there some other reason why semesterly still uses pngs over svgs?

**Comment by maxyeo** [comment]
There was a period of time when we were looking into developing a native mobile application for semester.ly on android and ios.  While SVG's hold a smaller file size and are better at scaling to different screen resolutions their support on native mobile devices aren't that great.  In addition, limited computing resources on a mobile device mean displaying a raster image is faster than calculating paths for an SVG.   Plans for a native mobile application have stopped so if you'd like to make our tutorial images SVG's I would be happy to assist!

**Comment by stewy33** [comment]
Ah, I see. Is there a photoshop or gimp file for the tutorial images or are the pngs all we have?
I tried to convert the pngs to a vectorized format but the vectorization process results in subpar images, unless I start from scratch, which I'm not very confident I'll be able to do well. If not, I'll close this issue.

**Comment by maxyeo** [comment]
We have a couple photoshop files available here: https://drive.google.com/drive/folders/0BzXL0vLjAYlLYldfVnM1N3E3bEE?usp=sharing Hope this helps!
