### ISSUE TITLE
Improve Advanced Search

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1068]
For area filters, have checkboxes for N,S, Writing intensive, etc. instead of only being able to pick groupings of the like. Additionally, move PE and BU stuff to the bottom or just somewhere so it doesn't clutter everything. Most of our users are undergraduates that don't need those options. This would allow us to change the layout of the modal so that we just have the normal N,S,Q,E,H area filters as accessible checkboxes on the side.

Add a number of credits filter.

Would also be fun to have a "I like my sleep" filter that rids of 9am classes or any classes before noon.

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
