### ISSUE TITLE
gCal dates

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1071]
in student/views.py the post() method where you create a calendar you hardcode in the dates for the semester but that's not always going to be the same. Not a big deal because classes always start around the same time but would be a quick and nice fix for a newbie

**Comment by kristinyim** [comment]
Also add options for intersession and summer while you're there

**Comment by lizziemarie** [comment]
Hi @kristinyim I'm interested in helping out here! Could you please guide me to the right place to add my fixes?
