### ISSUE TITLE
Adding Support for Bucknell University

### ISSUE THREAD

**Issue by icewing1996** [noahpresler/semesterly#1077]
I would like to add a new school. I followed the documentation and created a scaffolder.
I know that I need to develop a parser.
I don't know how I should structure my parsed JSON file though, so I tried ingesting existing schools by running
python manage.py ingest 
Unfortunately none of the schools worked.

I'm thinking about using scrapy for parsing. How can I make it work with ingest?
How do I structure the JSON file? 
Once I've done the parser and got the JSON, what else do I need to do to add a new school?
Any files I need to change?

**Comment by Boccca2014** [comment]
Hi @icewing1996 ,

This repository is now deprecated as of June 2021.
The new repository can be found [HERE](https://github.com/jhuopensource/semesterly).
If you still wish to integrate your university, note any issues, or make any suggestions, please place them in the new repository. Thank you!

Best,

Sebastian (@Boccca2014)
Current Program Manager of [Semester.ly](https://semester.ly/)
