### ISSUE TITLE
Invite your friends to take a course

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1102]

**Comment by kristinyim** [comment]
"Stay big picture with that invite your friends feature. Think big about how to meaningfully integrate it at the app level, in settings, and/or in the course modal
You can track analytics on it and save it to that user profile page. That way you could track the metric that they invite 3 friends in order to get pizza etc (if you create objects for each invite)
https://jhu.semester.ly/user/settings/"
- Noah

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in new repo!
