### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by kristinyim** [noahpresler/semesterly#1105]
Another idea: Semester.ly Chrome extension that turns any course code you write into a Semester.ly URL to the course
It changes the CSS for it and makes it link to our Semester.ly page (could exclude SIS or treat SIS differently though)
So if I typed EN.600.150 I could hover over it to see the course name etc (Max has the code to match regex even like 600.150 and there is this feature on the course modal where you can hover to get details) then click would bring to coruse modal
That's a fun one
Then you could ideate on how else to make a chrome extension useful
For example can you do other smart things on SIS to drive traffic to semester.ly
It could help with identifying course websites. If the extension finds a jhu domain webpage and it had the course code, name, and professor we could ask: is this the course page?

(Exclude blackboard)

If yes, and 2+ other people say yes we can add that url as the course url in the DB and link to it in the course modal
The extension could also integrate that GPA me extension I built as additional value. Finally remaking that and rebranding it under semesterly
We could even make it so we automatically bookmark all pages related to a course and then refind them categorized by course on semesterly or something like that

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do!
