### ISSUE TITLE
Updated parsing time

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#1111]
https://github.com/noahpresler/semesterly/blob/1391fb5ebb5a8e1a04a7cead7bdc056ac1b4b9cb/parsing/tasks.py#L28

Let's update this parsing time to be 3am?

**Comment by kristinyim** [comment]
I'm a bit confused by this. This is for celery? I'm assuming that you just want me to change it to (hour=03, minute=00) but since Celery isn't working how can I check that this works?

**Comment by alihacks** [comment]
This is configured as a scheduled task on the AWS Fargate cluster, I will update it.

**Comment by Boccca2014** [comment]
Closed, resolved above.
