### ISSUE TITLE
University of Toronto

### ISSUE THREAD

**Issue by RyanMarten** [noahpresler/semesterly#1146]
What happened to UofT support? The site exists at https://uoft.semester.ly/ still. Is it possible to update the website to have the most updated courses? 

Since Semesterly is open source now, how do we contribute and deploy to the uoft.semester.ly server?

**Comment by RyanMarten** [comment]
I saw that support was added here: https://github.com/noahpresler/semesterly/commit/1403de4c23c0a8af7f0af4af9192917c0c43516e
https://github.com/noahpresler/semesterly/pull/1087

But I don't think those changes were ever merged in? Is the team still supporting pull requests?

**Comment by Boccca2014** [comment]
Hi @RyanMarten,

This repository is now deprecated as of June 2021. 
The new repository can be found [HERE](https://github.com/jhuopensource/semesterly).
If you still wish to integrate your university, note any issues, or make any suggestions, please place them in the new repository. We apologize for the delayed response and hope to hear from you soon. Thank you!

Best,

Sebastian (@Boccca2014)
Current Program Manager of [Semester.ly](https://semester.ly/)
