### ISSUE TITLE
Support for Class of 2024

### ISSUE THREAD

**Issue by saad124ansari** [noahpresler/semesterly#1147]
Add 2024 as option when signing up, under the 'What's your graduating class year?' dropdown menu.

**Comment by Boccca2014** [comment]
Hi @saad124ansari,

This has been updated as of June 2021. Please refer to the [new repository](https://github.com/jhuopensource/semesterly) for any future changes. Thank you!

Best,

Sebastian (@Boccca2014)
Current Program Manager of [Semester.ly](https://semester.ly/)
