### ISSUE TITLE
JHU Course Canceled status shows all seats open

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#511]
Ex: AS.300.348

Cancelled class shows 25/25 open seats.

On Semesterly
![image](https://cloud.githubusercontent.com/assets/8674966/22513111/1fdb6ce0-e869-11e6-95d5-6529d8819026.png)

On SIS
![image](https://cloud.githubusercontent.com/assets/8674966/22513125/28d597b2-e869-11e6-9bd8-b0fb321fd8b7.png)

NOTE: confirmed that this issue persists for more than 24hrs suggesting that this is a case the parser itself needs to handle.

**Comment by Boccca2014** [comment]
@Boccca2014 need to check if this is still an issue
