### ISSUE TITLE
Miscellaneous Parser errors

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#564]
- [ ] Improper data extraction of *prereq* (notice "/coreq)" in description completes prereq)
![image](https://cloud.githubusercontent.com/assets/8674966/23860212/ae7d7a64-07dc-11e7-9f5a-742c0b2bc3c3.png)

- [ ] Number of open seats exceeds limit (Chapman Fall 2017)
![image](https://cloud.githubusercontent.com/assets/8674966/24385688/7527efac-1339-11e7-8484-9b291fbd0dd0.png)

- [ ] extra comma in professor (JHU Fall 2017)
![image](https://cloud.githubusercontent.com/assets/8674966/24386586/6a944996-133e-11e7-8a6d-b1c09757778b.png)

- [ ] invalid ISBN given, store textbook title #672 
![image](https://cloud.githubusercontent.com/assets/8674966/25191929/44266bd6-24ff-11e7-986f-e7b5abd430f5.png)

- [ ] Start and end time are the same
![image](https://user-images.githubusercontent.com/8674966/29334878-bf47975c-81bd-11e7-95a8-5842f7a7e1bb.png)

--------------------------

**Comment by Boccca2014** [comment]
@Boccca2014 need to check parser
