### ISSUE TITLE
Display Info when user trys to disable settings not in correct order

### ISSUE THREAD

**Issue by mnm364** [noahpresler/semesterly#694]
It is confusing that you cannot disable some setttings without first disabling the bottom ones. It makes sense but a message should be generated to inform the user of this in the case they try clicking on "Yes" and it doesn't work.

![image](https://cloud.githubusercontent.com/assets/8674966/24510745/0fdd113a-1538-11e7-86e8-aa633790407d.png)

**Comment by Boccca2014** [comment]
@Boccca2014 Should be an easy fix, will add issue to new repo
