### ISSUE TITLE
Refactor OAUTH redirect URIs

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#987]
Currently, everytime we add a school we must add the subdomain as a whitelisted URI on both the Facebook and Google OAUTH api. They do not accept wildcards like `*.semester.ly`

 This causes substantial issues, especially during rapid, open source expansion. 

### To mitigate:

Make `semester.ly` without a subdomain accept all of the OAUTH related requests and redirect the user. The oauth could pass a string parameter which might redirect the user for instance.

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
