### ISSUE TITLE
Integrate RateMyProf Ratings

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#988]
Some students rely on rate my professor for course reviews. In order to support this, semester.ly could add a ratemyprof url field to section (or to the Professor model in the future once it exists). 

Then, in the course modal, if filled in, a link would appear that would open the ratemyprof for the professor in a new window.

### Important Distinction:
We would not scrape or store their ratings. Only a url which we would allow users to follow directly to the ratemyprof website.

**Comment by shoe17** [comment]
I'm going to take this! Seems nice in order to ease myself into working on open source projects.

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
