### ISSUE TITLE
Create a Professor Model

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#989]
Currently professors are stored as strings on sections. This should be refactored such that professor is its own model (perhaps in the courses, or its own app). 

Sections would then have a many to many field relating it to many professors. 

Professors could then easily be integrated into search (searching by professor for courses, potentially adding a professor modal one can open by searching for a professor and clicking on their result with all of their evals). 

Evals should then be updated to reference a professor 

## Probably fields:

- Name
- School

**Comment by mnm364** [comment]
Repeat of #94?

**Comment by Boccca2014** [comment]
@Boccca2014 Will try to do in the new repo!
