### ISSUE TITLE
Cannot find manifest.json

### ISSUE THREAD

**Issue by noahpresler** [noahpresler/semesterly#993]
![image](https://user-images.githubusercontent.com/7767915/28998499-95231ae8-79e1-11e7-8479-652d9477979b.png)

**Comment by maxyeo** [comment]
@felixzhuologist were you able to figure out what was happening here?

**Comment by felixzhuologist** [comment]
no i thought you had fixed it by adding a line to settings.py. I don't see that change anymore so maybe it got removed somewhere?
